services:
  db:
    image: mariadb 
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: Trimmer-Onslaught-Spherical-Overjoyed-Poise-Overrate-Botanical-Humorous-Crewless5-Fetch
      MYSQL_DATABASE: customers
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
  website:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - default
    ports:
      - 8042:80
    volumes:
      - ./html:/var/www/html

networks:
  default: {}
